vulhain:
  # Placeholders:
  # %vl%  the current check vl
  # %check% the check for what the player failed
  # %type%  the type of the check for what the player failed
  # %exp% if the check is experimental or not
  # %probability% the chance for the player to cheat
  # %player% the presumed cheater
  alert-message: "&cVulhain &7/ &d%player% &7flagged &7%exp% &d%check% &7(&dType %type%&7)&7 (&c%vl%/%maxvl%&7)"
  punish-command: "kick %player% &cVulhain&7/ Cheating"
checks:
  movement:
    fly:
      a:
        enabled: true
        max-vl: 10
        buffer: 2
        punish: false
      b:
        enabled: true
        max-vl: 10
        buffer: 4
        punish: false
    step:
      a:
        enabled: true
        max-vl: 10
        buffer: 2
        punish: false
  combat:
    killaura:
      a:
        enabled: true
        max-vl: 10
        buffer: 6
        punish: false
    aim:
      a:
        enabled: true
        max-vl: 10
        buffer: 2
        punish: false
      b:
        enabled: true
        max-vl: 10
        buffer: 4
        punish: false